# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# Modus Operandi
include current-theme.conf
# END_KITTY_THEME

font_family MesloLGS Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto

# Cf https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font
# kitty has a builtin NERD font and will use it for symbols not found in any other font on your system.
# If you have patched fonts on your system they might be used instead for NERD symbols,
# so to force kitty to use the pure NERD font for NERD symbols, add the following line to kitty.conf
symbol_map U+e000-U+e00a,U+e0a0-U+e0a2,U+e0a3,U+e0b0-U+e0b3,U+e0b4-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ea60-U+ec1e,U+ed00-U+efce,U+f000-U+f2ff,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font Mono

font_size 13.0

hide_window_decorations yes

background_image /home/lofic/Documents/images/wallpapers/wbg-small.png
background_image_layout scaled

# does not work with
# set bell-style visible
# in ~/.inputrc :
enable_audio_bell no
visual_bell_duration 0.5
visual_bell_color #FFFFFF

# grid as first default layout
enabled_layouts splits,grid,stack,fat,horizontal,tall,vertical

map kitty_mod+enter launch --cwd=current --type=window
map kitty_mod+tab next_window
map kitty_mod+x toggle_layout stack

# hOrizontal split (same shortcut as in terminator)
map kitty_mod+o launch --location=hsplit --cwd=current
# vErtical split (same shortcut as in terminator)
map kitty_mod+e launch --location=vsplit --cwd=current

# Defaults, for reminder
# Cf https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts
# kitty_mod ctrl+shift
# map kitty_mod+l next_layout
map ctrl+shift+equal change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0
# map kitty_mod+f11 toggle_fullscreen
# Or run with :
# ~/.local/kitty.app/bin/kitty --start-as=fullscreen
# Resize tiles : Press ctrl+shift+r to enter resizing mode and follow the on-screen instructions (S: shorter, T: taller)
